# Generated by Django 3.1.2 on 2020-12-29 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_octave', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=50)),
                ('hole_1', models.BooleanField(default=False)),
                ('hole_2', models.BooleanField(default=False)),
                ('hole_3', models.BooleanField(default=False)),
                ('hole_4', models.BooleanField(default=False)),
                ('hole_5', models.BooleanField(default=False)),
                ('hole_6', models.BooleanField(default=False)),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tabs.song')),
            ],
        ),
    ]
